
autoscaling:
  enabled: true

gateway:
  enabled: true

ingress:
  enabled: false
  extraHosts:
    - name: netbox.dev
    - name: netbox.stg
  extraPaths:
    - path: /netbox

persistence:
  accessModes:
  - ReadWriteMany

postgresql:
  auth:
    postgresPassword: j6vdHYFm2ZZ6168L0WC2Kyh35UTiVctgkCAWLJp4RAQXqDpUvqdDCeS3xJ5uJxBe
    # username: netbox_user
    password: mRY5pxyx1aiDZPKHSCcdjXqSXLSYkA

# redis:
#   auth:
#     password: 9FYGZS1ziN31KjP9ZB0TRgXjD9zGj6

secretKey: yA9ZzZYMJdN3iVEqjYVhbU1kxnHEnqZM9zKhcPNx5Z3EFZt6VEBZQHBHM2trPPLQ

superuser:
  password: QqbpZ2R598RqUMVeF0BNSdGjS581mtFD2Bu30a0pYVk9SCSi2qBcK2F6tH8XhKCH
  apiToken: cEf9xgxG04Bvi8Q6n3WYxX4QRQ1LpVH6WKpGMxKiQLNDegc3b9EEgKkY8Qn2krK6

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    labels:
      release: kube-prometheus-stack

test:
  image:
    repository: busybox
    tag: 1.36.1
    pullPolicy: IfNotPresent

  resources: {}

housekeeping:
  schedule: '*/5 * * * *'