postgresql:
  enabled: true
  # auth:
  #   username: netbox_user
  #   password: "mRY5pxyx1aiDZPKHSCcdjXqSXLSYkA"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack