##ref: https://raw.githubusercontent.com/openebs/mayastor-control-plane/master/deploy/csi-deployment.yaml

{{- if .Values.csiController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-csi-controller" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: csi-controller
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: csi-controller
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: csi-controller
        {{- if .Values.podLabels }}
          {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      {{- include "mayastor.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.ioEngine.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.ioEngine.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mayastor.serviceAccountName" . }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      initContainers:
        - name: api-rest-probe
          image: busybox:latest
          command:
            - sh
          args:
            - -c
            - |
              trap "exit 1" TERM
              until nc -vzw 5 {{ include "mayastor.apiRest.fullname" . }} {{ .Values.apiRest.service.ports.https }}
              do
                echo "$(date) Waiting for REST API endpoint to become available"
                sleep 1
              done
      containers:
        - name: csi-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--feature-gates=Topology=true"
            - "--strict-topology=false"
            - "--default-fstype=ext4"
            - "--v=2"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
            - name: NAMESPACE
              valueFrom:
                  fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                  fieldPath: metadata.name
          imagePullPolicy: {{ .Values.csiController.image.pullPolicy | quote }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=2"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
            - name: NAMESPACE
              valueFrom:
                  fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                  fieldPath: metadata.name
          imagePullPolicy: {{ .Values.csiController.image.pullPolicy | quote }}
          {{- if .Values.csiController.attacher.resources }}
          resources: {{ toYaml .Values.csiController.attacher.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-controller
          image: {{ include "mayastor.csiController.image" . }}
          imagePullPolicy: {{ .Values.csiController.image.pullPolicy | quote }}
          args:
            - "--csi-socket=/var/lib/csi/sockets/pluginproxy/csi.sock"
            - "--rest-endpoint=http://{{ include "mayastor.apiRest.fullname" . }}:{{ .Values.apiRest.service.ports.https }}"
            {{- range $key, $val := .Values.ioEngine.nodeSelector }}
            - "--io-engine-selector={{ $key }}:{{ $val }}"
            {{- end }}
          env:
            - name: RUST_BACKTRACE
              {{- if .Values.diagnosticMode.enabled }}
              value: full
              {{- else }}
              value: full
              {{- end }}
            - name: RUST_LOG
              value: {{ .Values.csiController.logLevel }}
          {{- if .Values.csiController.resources }}
          resources: {{ toYaml .Values.csiController.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}
{{- end }}