#####################################
## FreeRADIUS ConfigMap config
#####################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-env" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.modsEnabled.sql.enabled }}
  FREERADIUS_MODS_SQL_DIALECT: {{ .Values.modsEnabled.sql.dialect }}
  FREERADIUS_MODS_SQL_SERVER: {{ include "freeradius.databaseHost" . | quote }}
  FREERADIUS_MODS_SQL_PORT: {{ include "freeradius.databasePort" . }}
  FREERADIUS_MODS_SQL_LOGIN: {{ include "freeradius.databaseUser" . | quote }}
  # FREERADIUS_MODS_SQL_PASSWORD: {{ .Values.modsEnabled.sql.password }}
  FREERADIUS_MODS_SQL_DB: {{ include "freeradius.databaseName" . | quote }}
  FREERADIUS_MODS_SQL_TABLE_CLIENT: {{ .Values.modsEnabled.sql.tableClient }}
  {{- end }}

  FREERADIUS_ENABLE_TLS: {{ ternary "true" "false" .Values.tls.enabled | quote }}

  FREERADIUS_SITES_STATUS_PORT: {{ .Values.containerPorts.status | quote }}
  #FREERADIUS_SITES_STATUS_SECRET: {{ .Values.sitesEnabled.status.secret | quote }}

  FREERADIUS_SITES_DEFAULT_PORT: {{ .Values.containerPorts.auth | quote }}
  FREERADIUS_SITES_DEFAULT_AUTH_PORT: {{ .Values.containerPorts.auth | quote }}
  FREERADIUS_SITES_DEFAULT_ACCT_PORT: {{ .Values.containerPorts.acct | quote }}
  FREERADIUS_SITES_DEFAULT_COA_PORT: {{ .Values.containerPorts.coa | quote }}

  
