{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: freeradius
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  ingress:
    - ports:
        - port: {{ .Values.containerPorts.auth }}
        - port: {{ .Values.containerPorts.acct }}
        {{- if .Values.tls.enabled }}
        - port: {{ .Values.containerPorts.radsec }}
        {{- end }}
        {{- if .Values.metrics.enabled }}
        - port: {{ .Values.containerPorts.metrics }}
        {{- end }}
        {{- if .Values.sitesEnabled.coa.enabled }}
        - port: {{ .Values.containerPorts.coa }}
        {{- end }}
        {{- if .Values.sitesEnabled.status.enabled }}
        - port: {{ .Values.containerPorts.status }}
        {{- end }}
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{ template "common.names.fullname" . }}-client: "true"
        - podSelector:
            matchLabels: {{- include "common.labels.matchLabels" . | nindent 14 }}
              app.kubernetes.io/component: freeradius
        {{- if .Values.networkPolicy.additionalRules }}
          {{- include "common.tplvalues.render" (dict "value" .Values.networkPolicy.additionalRules "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
{{- end }}