##ref: https://raw.githubusercontent.com/openebs/mayastor-control-plane/master/deploy/msp-deployment.yaml

{{- if .Values.mspOperator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-msp-operator" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: msp-operator
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: msp-operator
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: msp-operator
        {{- if .Values.podLabels }}
          {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "mayastor.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "mayastor.serviceAccountName" . }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      initContainers:
        - command:
            - sh
            - -c
            - trap "exit 1" TERM; until nc -vz mayastor-nats 4222; do echo "Waiting for nats..."; sleep 1; done;
          image: busybox:latest
          name: nats-probe
        - command:
            - sh
            - -c
            - trap "exit 1" TERM; until nc -vz mayastor-etcd 2379; do echo "Waiting for etcd..."; sleep 1; done;
          image: busybox:latest
          name: etcd-probe
      containers:
        - name: msp-operator
          image: {{ include "mayastor.mspOperator.image" . }}
          imagePullPolicy: {{ .Values.mspOperator.image.pullPolicy | quote }}
          args:
            - "-e http://mayastor-rest:8081"
            - "--interval=30s"
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RUST_LOG
              value: info,msp_operator=info
            - name: RUST_BACKTRACE
              value: full
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
            requests:
              cpu: 50m
              memory: 16Mi
{{- end }}