apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
description: This priority class should be used for the Mayastor CSI driver node deployment only.
globalDefault: false
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: csi-node
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
  name: {{ printf "%s-critical" (include "mayastor.csiNode.fullname" .) }}
value: 910000000