{{- if .Values.csiDriver.create -}}
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: mayastor.openebs.io
spec:
  podInfoOnMount: {{ .Values.csiDriver.podInfoOnMount }}
  attachRequired: {{ .Values.csiDriver.attachRequired }}
{{- end }}