affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: node-role.kubernetes.io/worker
          operator: Exists

istio:
  enabled: true
  hosts:
    - "adminer.app.tazbiya.com"

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists