affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: node-role.kubernetes.io/worker
          operator: Exists

ingress:
  enabled: true
  hosts:
    - adminer.dxm.nainggolan.id

istio:
  enabled: true
  ingressGateway: ingress-app


tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
