{{- range $gateway := .Values.gateways }}
{{- if and $gateway.enabled $.Values.pdb.create }}
apiVersion: {{ include "common.capabilities.policy.apiVersion" $ }}
kind: PodDisruptionBudget
metadata:
  name: {{ .name }}
  namespace: {{ include "gateways.names.namespace" $ | quote }}
  labels: {{ include "gateway.labels.standard" (dict "name" .name "revision" .revision "context" $) | nindent 4 }}
    install.operator.istio.io/owning-resource: {{ $.Values.ownerName | default "unknown" }}
    {{- if $.Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" $.Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.pdb.minAvailable }}
  minAvailable: {{ $.Values.pdb.minAvailable | int }}
  {{- end }}
  {{- if $.Values.pdb.minAvailable }}
  maxUnavailable: {{ $.Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels: {{ include "common.labels.matchLabels" $ | nindent 6 }}
      istio: {{ .name }}
      istio.io/gateway-name: {{ .name }}
---
{{- end }}
{{- end }}