{{- if .Values.rbac.create }}
apiVersion: {{ include "gateways.capabilities.rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ include "gateways.names.fullname" . | quote }}
  namespace: {{ include "gateways.names.namespace" . | quote }}
  labels: {{- include "gateways.labels.common" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "gateways.tplvalues.render" (dict "value" .Values.commonAnnotations "context" .) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
    {{- if .Values.rbac.rules }}
      {{- include "gateways.tplvalues.render" (dict "value" .Values.rbac.rules "context" .) | nindent 2 }}
    {{- end }}
---
{{- end }}