{{- if and .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" $ }}
kind: RoleBinding
metadata:
  name: {{ include "gateways.names.fullname" . }}
  namespace: {{ include "gateways.names.namespace" . | quote }}
  labels: {{- include "gateways.labels.common" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "common.names.fullname" . | quote }}
subjects:
  {{- range $gateway := .Values.gateways }}
  {{- if and $gateway.enabled (and .serviceAccount .serviceAccount.create)}}
  - kind: ServiceAccount
    name: {{ include "gateway.rbac.serviceAccountName" ( dict "gatewayValues" $gateway "context" $ ) }}
  {{- end }}
  {{- end }}
{{- end -}}