{{- range $gateway := .Values.gateways }}
{{- if and $.Values.rbac.create (default "true" $gateway.rbac.create) }}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ $gateway.name | quote }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels:
    release: {{ $.Release.Name }}
    istio.io/rev: {{ $gateway.revision | default "default" }}
    install.operator.istio.io/owning-resource: {{ $.Values.ownerName | default "unknown" }}
    operator.istio.io/component: {{ $.Values.operator.component }}
    {{- if $.Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" $.Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $.Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "common.names.fullname" $ | quote }}
subjects:
- kind: ServiceAccount
  name: {{ $gateway.name }}-sa
---
{{- end }}
{{- end }}