{{- range $gateway := .Values.gateways }}
{{- if and .enabled $.Values.serviceAccount.create (and .serviceAccount .serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .serviceAccount.automountServiceAccountToken | default true }}
metadata:
  name: {{ printf "%s-sa" .name | quote }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{ include "gateway.labels.standard" (dict "name" .name "revision" .revision "context" $) | nindent 4 }}
    release: {{ $.Release.Name }}
    install.operator.istio.io/owning-resource: {{ $.Values.ownerName | default "unknown" }}
    operator.istio.io/component: "IngressGateways"
    {{- if $.Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" $.Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- $mergedAnnotations := merge $.Values.serviceAccount.annotations $.Values.commonAnnotations (and .serviceAccount .serviceAccount.annotations)}}
  {{- if $mergedAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $mergedAnnotations "context" $) | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}