{{ $gateway := index .Values "gateways" "istio-ingressgateway" }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ $gateway.name }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    istio: {{ $gateway.name }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.pdb.create }}
  replicas: {{ default 1 $gateway.replicaCount | int }}
  {{- end }}
  selector:
    matchLabels:
      istio: {{ $gateway.name }}
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        {{- if .Values.metrics.enabled }}
          {{- include "common.tplvalues.render" (dict "value" .Values.metrics.annotations "context" $) | nindent 8 }}
        {{- end }}
        {{- if $gateway.podAnnotations }}
          {{- include "common.tplvalues.render" (dict "value" $gateway.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        istio: {{ $gateway.name }}
        sidecar.istio.io/inject: "true"
        {{- if $gateway.revision }}
        istio.io/rev: {{ $gateway.revision | quote }}
        {{- end }}
        {{- if $gateway.podLabels }}
          {{- include "common.tplvalues.render" (dict "value" $gateway.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "gateway.imagePullSecrets" . | nindent 6 }}
      {{- if $gateway.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" $gateway.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if $gateway.podSecurityContext.enabled }}
      securityContext: {{- omit $gateway.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $gateway.name }}-sa
      {{- if $gateway.schedulerName }}
      schedulerName: {{ $gateway.schedulerName }}
      {{- end }}
      {{- if $gateway.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" $gateway.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if $gateway.priorityClassName }}
      priorityClassName: {{ $gateway.priorityClassName | quote }}
      {{- end }}
      {{- if $gateway.runtimeClassName }}
      runtimeClassName: {{ $gateway.runtimeClassName }}
      {{- else if .Values.runtimeClassName }}
      runtimeClassName: {{ .Values.runtimeClassName | quote }}
      {{- end }}
      {{- if $gateway.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" $gateway.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" $gateway.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" $gateway.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" $gateway.nodeAffinityPreset.type "key" $gateway.nodeAffinityPreset.key "values" $gateway.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if $gateway.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" $gateway.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if $gateway.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" $gateway.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if $gateway.initContainers }}
      initContainers:
        {{- include "common.tplvalues.render" (dict "value" $gateway.initContainers "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: istio-proxy
          # "auto" will be populated at runtime by the mutating webhook. See https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection
          image: auto
          imagePullPolicy: {{ $gateway.image.pullPolicy | quote }}
          {{- if $gateway.containerSecurityContext.enabled }}
          securityContext: {{- omit $gateway.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          env:
            {{- with $gateway.networkGateway }}
            - name: ISTIO_META_REQUESTED_NETWORK_VIEW
              value: "{{.}}"
            {{- end }}
            {{- if $gateway.extraEnvVars }}
              {{- include "common.tplvalues.render" (dict "value" $gateway.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if or $gateway.extraEnvVarsCM $gateway.extraEnvVarsSecret }}
          envFrom:
            {{- if $gateway.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" $gateway.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if $gateway.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" $gateway.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- end }}
          ports:
            - containerPort: 15090
              protocol: TCP
              name: http-envoy-prom
          {{- if $gateway.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" $gateway.customStartupProbe "context" $) | nindent 12 }}
          {{- else if $gateway.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit $gateway.startupProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if $gateway.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" $gateway.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if $gateway.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: {{ $gateway.livenessProbe.initialDelaySeconds | int }}
            periodSeconds: {{ $gateway.livenessProbe.periodSeconds | int }}
            timeoutSeconds: {{ $gateway.livenessProbe.timeoutSeconds |int }}
            failureThreshold: {{ $gateway.livenessProbe.failureThreshold | int }}
            successThreshold: {{ $gateway.livenessProbe.successThreshold | int }}
          {{- end }}
          {{- if $gateway.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" $gateway.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if $gateway.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit $gateway.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if $gateway.resources }}
          resources: {{- toYaml $gateway.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
          volumeMounts:
            {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.sidecars }}
          {{- include "common.tplvalues.render" (dict "value" .Values.sidecars "context" $) | trim | nindent 8 }}
        {{- end }}
      {{- if .Values.extraVolumes }}
      volumes:
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes "context" $) | nindent 8 }}
      {{- end }}
