{{ - if (include "common.capabilities.networkingGateway.apiVersion" $) }}
{{- range $gateway, $gatewayName := .Values.gateways }}
apiVersion: {{ include "common.capabilities.networkingGateway.apiVersion" $ }}
kind: Gateway
metadata:
  name: {{ .name }}
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  addresses:
    - value: {{ printf "%s.%s.svc.%s" .name (include "common.names.namespace" $) $.Values.clusterDomain }}
      type: Hostname
  listeners:
  - name: http2
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
  {{- if $gatewayName.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" $gatewayName.service.extraPorts "context" $) | nindent 2 }}
  {{- end }}
---
{{- end }}
{{- end }}