{{- range $gateway, $value := .Values.gateways }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  {{- $mergedAnnotations := merge .service.annotations $.Values.commonAnnotations }}
  {{- if $mergedAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $mergedAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    istio: {{ .name }}
    release: {{ $.Release.Name }}
    istio.io/rev: {{ .revision | default "default" }}
    install.operator.istio.io/owning-resource: {{ $.Values.ownerName | default "unknown" }}
    operator.istio.io/component: {{ $.Values.operator.component }}
    {{- if $.Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: {{ default "LoadBalancer" .service.type }}
  {{- if and .service.clusterIP (eq .service.type "ClusterIP") }}
  clusterIP: {{ .service.clusterIP }}
  {{- end }}
  {{- if and .service.externalTrafficPolicy (or (eq .service.type "LoadBalancer") (eq .service.type "NodePort")) }}
  externalTrafficPolicy: {{ .service.externalTrafficPolicy | quote }}
  {{- end }}
  ipFamilyPolicy: {{ default "SingleStack" .service.ipFamilyPolicy }}
  {{- if and (eq .service.type "LoadBalancer") (not (empty .service.loadBalancerClass)) }}
  loadBalancerClass: {{ .service.loadBalancerClass }}
  {{- end }}
  {{- if (and (eq .service.type "LoadBalancer") (not (empty .service.loadBalancerIP))) }}
  loadBalancerIP: {{ .service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .service.type "LoadBalancer") (not (empty .service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if .service.sessionAffinity }}
  sessionAffinity: {{ default "None" .service.sessionAffinity }}
  {{- end }}
  {{- if .service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  ports:
  {{- if .networkGateway }}
    - name: status-port
      port: 15021
      targetPort: 15021
    - name: tls
      port: 15443
      targetPort: 15443
    - name: tls-istiod
      port: 15012
      targetPort: 15012
    - name: tls-webhook
      port: 15017
      targetPort: 15017
  {{- else }}
    {{- range $key, $port := .service.ports }}
    - name: {{ $key }}
      port: {{ $port | int }}
      protocol: TCP
      targetPort: {{ $port }}
      {{- if (and (or (eq $value.service.type "NodePort") (eq $value.service.type "LoadBalancer")) (coalesce $.service.nodePorts.http2 $.service.nodePort)) }}
      nodePort: {{ coalesce $value.service.nodePorts.http2 $value.service.nodePort }}
      {{- else if eq $value.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- end }}
  {{- end }}
  selector: {{ include "common.labels.matchLabels" . | nindent 4 }}
    istio: {{ .name }}
---
{{- end }}