{{- if .Values.serviceAccount.create }}
{{- range $gateway, $val := .Values.gateways }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ $.Values.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ printf "%s-sa" .name }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    istio: {{ .name }}
    release: {{ $.Release.Name }}
    istio.io/rev: {{ .revision | default "default" }}
    install.operator.istio.io/owning-resource: {{ $.Values.ownerName | default "unknown" }}
    operator.istio.io/component: "IngressGateways"
    {{- include "common.labels.standard" . | nindent 4 }}
  {{- $mergedAnnotations := merge $.Values.serviceAccount.annotations $.Values.commonAnnotations }}
  {{- if $mergedAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $mergedAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}