{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: metrics
spec:
  groups:
    - name: {{ include "common.names.fullname" . }}
      rules:
        - alert: UnifiPollerAbsent
          annotations:
            description: Unifi Poller has disappeared from Prometheus service discovery.
            summary: Unifi Poller is down.
          expr: |
            absent(up{job=~".*{{ include "common.names.fullname" . }}.*"} == 1)
          for: 5m
          labels:
            severity: critical
        {{- with .Values.metrics.prometheusRule.rules }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
{{- end }}
