{{- if (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: unifi
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  unifi-password: {{ include "common.secrets.passwords.manage" (dict "secret" ( include "common.names.fullname" .) "key" "unifi-password" "providedValues" (list "unifiPassword") "context" $) }}
  {{- if and (not .Values.mongodb.enabled) (not .Values.externalDatabase.existingSecret) }}
  mongodb-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.influxdb.enabled .Values.influxdb.setDefaultUser.enabled .Values.influxdb.setDefaultUser.user.password }}
  influxdb-password: {{ .Values.influxdb.setDefaultUser.user.password | b64enc | quote }}
  {{- end }}
{{- end }}