gateways:
  - name: webapps
    enabled: true

    service:
      ipFamilyPolicy: PreferDualStack


  - name: freeradius
    enabled: true

    service:
      extraPorts:
        - name: acct
          port: 1813
          protocol: UDP
        - name: auth
          port: 1812
          protocol: UDP
        - name: coa
          port: 3799
          protocol: UDP
        - name: radsec
          port: 2083
          protocol: UDP

      ipFamilyPolicy: PreferDualStack

  
