gateways:
  - name: webapps
    enabled: true
    rbac:
      create: true

    service: {}

    serviceAccount:
      create: true
  
  - name: freeradius
    enabled: true
    rbac:
      create: true

    service: {}

    serviceAccount:
      create: true

  
