gateways:
  - name: webapps
    enabled: true
    rbac:
      create: true

    service:
      ipFamilyPolicy: PreferDualStack

    serviceAccount:
      create: true
  
  - name: freeradius
    enabled: true

    containerPorts: {}

    rbac:
      create: true

    service:
      extraPorts:
        - name: acct
          port: 1813
          protocol: UDP
        - name: auth
          port: 1812
          protocol: UDP
        - name: coa
          port: 3799
          protocol: UDP
        - name: radsec
          port: 2083
          protocol: UDP

      ipFamilyPolicy: PreferDualStack

    serviceAccount:
      create: true

  
