#####################################
## FreeRADIUS ConfigMap config
#####################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: freeradius-config
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- if .Values.modsEnabled.sql.enabled }}
  FREERADIUS_MODS_SQL_DIALECT: {{ .Values.modsEnabled.sql.dialect }}
  FREERADIUS_MODS_SQL_SERVER: {{ .Values.modsEnabled.sql.server }}
  FREERADIUS_MODS_SQL_PORT: {{ .Values.modsEnabled.sql.port | quote }}
  FREERADIUS_MODS_SQL_LOGIN: {{ .Values.modsEnabled.sql.login }}
  FREERADIUS_MODS_SQL_PASSWORD: {{ .Values.modsEnabled.sql.password }}
  FREERADIUS_MODS_SQL_DB: {{ .Values.modsEnabled.sql.radiusdb }}
  FREERADIUS_MODS_SQL_TABLE_CLIENT: {{ .Values.modsEnabled.sql.tableClient }}
  {{- end }}

  FREERADIUS_SITES_STATUS_PORT: {{ .Values.sitesEnabled.status.port | quote }}
  FREERADIUS_SITES_STATUS_SECRET: {{ .Values.sitesEnabled.status.secret }}

  FREERADIUS_SITES_DEFAULT_PORT: "1812"

