#####################################
## FreeRADIUS ConfigMap mods-enabled
#####################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: freeradius-sites
  namespace: {{ .Release.Namespace | quote }}
{{- $Global := . }}
data:
  default: |-
{{ tpl (.Files.Get "files/sites-enabled/default") . | nindent 4 }}
  status: |-
{{ tpl (.Files.Get "files/sites-enabled/status") . | nindent 4 }}