{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1beta1" }}
{{- if and .Values.istio.enabled .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    istio: {{ .Values.istio.gateway.ingressGateway }}
  servers:
  {{- range .Values.istio.gateway.servers }}
    - port:
        {{- with .port }}
        number: {{ .number }}
        name: {{ .name }}
        protocol: {{ .protocol }}
        {{- end }}
      hosts:
        {{- range $.Values.istio.hosts }}
        - {{ . | quote }}
        {{- end }}    
      {{- if .tls }}
      tls:
        {{- with .tls }}
        credentialName: {{ include "istioCertificateSecret" $ }}
        mode: {{ .mode }}
        {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}