{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1beta1" }}
{{- if and .Values.istio.enabled .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    istio: {{ .Values.istio.ingressGateway }}
  servers:
    {{- range .Values.istio.gateway.servers }}
    - port:
        name: {{ .name }}
        number: {{ .port }}
        protocol: {{ .protocol }}
      hosts:
        - {{ $.Values.ingress.hostname | quote }}
        {{- range $.Values.ingress.extraHosts }}
        - {{ .name | quote }}
        {{- end }}
      {{- if and (eq .protocol "HTTPS") (or $.Values.ingress.tls $.Values.ingress.extraTls) }}
      tls:
        credentialName: {{ printf "%s-tls" $.Values.ingress.hostname }}
        mode: SIMPLE
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}