{{- if (include "common.capabilities.istioNetworking.apiVersion" .) -}}
apiVersion: {{ include "common.capabilities.istioNetworking.apiVersion" . }}
kind: ServiceEntry
metadata:
  name: {{ include "netbox.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  hosts:
    - netbox.dev
    - github.com
    - api.github.com
  location: MESH_EXTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS
{{- end -}}