apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ printf "%s-io-engine" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: io-engine
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: io-engine
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: io-engine
        openebs.io/logging: "true"
        {{- if .Values.podLabels }}
          {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      {{- include "mayastor.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.ioEngine.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      initContainers:
        - name: agent-core-probe
          image: busybox:latest
          command:
            - sh
          args:
            - -c
            - trap "exit 1" TERM; until nc -vzw 5 {{ include "mayastor.agentCore.fullname" . }} {{ .Values.agentCore.service.port.grpc }}; do date; echo "Waiting for agent-core-grpc services..."; sleep 1; done;
        - name: etcd-probe
          image: busybox:latest
          command:
            - sh
          args:
            - -c
            - trap "exit 1" TERM; until nc -vzw 5 {{ include "mayastor.etcd.fullname" . }} {{ .Values.etcd.service.port }}; do date; echo "Waiting for etcd..."; sleep 1; done;
      containers:
        - name: io-engine
          image: {{ include "mayastor.ioEngine.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.command "context" $) | nindent 12 }}
          {{- else }}
          command:
            - io-engine
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.args "context" $) | nindent 12 }}
          {{- else }}
          args:
            # The -l argument accepts cpu-list. Indexing starts at zero.
            # For example -l 1,2,10-20 means use core 1, 2, 10 to 20.
            # Note: Ensure that the CPU resources are updated accordingly.
            #       If you use 2 CPUs, the CPU: field should also read 2.
            - "-g $(MY_POD_IP)"
            - "-l {{ include "mayastor.ioEngine.cpuFlag" . }}"
            - "-p {{ include "mayastor.etcd.fullname" . }}:{{ .Values.etcd.service.port }}"
            - "-R https://{{ include "mayastor.agentCore.fullname" . }}:{{ .Values.agentCore.service.port.grpc }}"
            - "-y /var/local/io-engine/config.yaml"
          {{- end }}
          env:
            - name: NVME_QPAIR_CONNECT_ASYNC
              value: "true"
            - name: NVMF_TCP_MAX_QUEUE_DEPTH
              value: "32"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RUST_BACKTRACE
              {{- if .Values.diagnosticMode.enabled }}
              value: full
              {{- else }}
              value: "1"
              {{- end }}
            - name: RUST_LOG
              value: {{ .Values.ioEngine.logLevel }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: device
              mountPath: /dev
            - name: udev
              mountPath: /run/udev
            - name: dshm
              mountPath: /dev/shm
            - name: configlocation
              mountPath: /var/local/io-engine/
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
          ports:
          - name: io-engine
            containerPort: {{ .Values.ioEngine.containerPorts.io-engine }}
            protocol: TCP
        {{- if .Values.metrics.enabled }}
        - name: metrics-exporter-pool
          image: {{ include "mayastor.apiRest.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          command:
            - metrics-exporter-pool
          ports:
            - name: http-metrics
              containerPort: 9502
              protocol: TCP
        {{- end }}
      volumes:
      - name: device
        hostPath:
          path: /dev
          type: Directory
      - name: udev
        hostPath:
          path: /run/udev
          type: Directory
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "1Gi"
      - name: hugepage
        emptyDir:
          medium: HugePages
      - name: configlocation
        hostPath:
          path: /var/local/io-engine/
          type: DirectoryOrCreate