apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ printf "%s-csi" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: mayastor-csi
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: mayastor-csi
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: mayastor-csi
        {{- if .Values.podLabels }}
          {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      hostNetwork: true
      nodeSelector:
        openebs.io/engine: mayastor
        kubernetes.io/arch: amd64
      {{- include "mayastor.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "mayastor.serviceAccountName" . }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      # NOTE: Each container must have mem/cpu limits defined in order to
      # belong to Guaranteed QoS class, hence can never get evicted in case of
      # pressure unless they exceed those limits. limits and requests must be
      # the same.
      containers:
      - name: mayastor-csi-plugin
        {{- if .Values.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
        {{- else if .Values.command }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.command "context" $) | nindent 12 }}
        {{- else }}
        command:
          {{- if or (eq .Values.diagnosticMode.environment "development") (eq .Values.diagnosticMode.environment "dev") -}}
          - csi-node
          {{- else -}}
          - mayastor-csi
          {{- end -}}
        {{- end }}
        {{- if .Values.diagnosticMode.enabled }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
        {{- else if .Values.args }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.args "context" $) | nindent 12 }}
        {{- else }}
        args:
          - "--csi-socket=$(CSI_SOCKET_ADDRESS)"
          - "--node-name=$(MY_NODE_NAME)"
          - "--grpc-endpoint=$(MY_POD_IP):10199"
          {{- if .Values.csi.nvme.io_timeout_enabled }}
          - "--nvme-core-io-timeout={{ .Values.csi.nvme.io_timeout }}"
          {{- end }}
          - "-v"
        {{- end }}
        image: {{ include "mayastor.csi.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        securityContext:
          privileged: true
        env:
          - name: CSI_SOCKET_ADDRESS
            value: {{ .Values.csi.socketAddress | quote }}
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: RUST_BACKTRACE
            value: full
          {{- if .Values.moac }}
          - name: MOAC
            value: "true"
          {{- end }}
        resources:
          limits:
            cpu: "100m"
            memory: "50Mi"
          requests:
            cpu: "100m"
            memory: "50Mi"
        volumeMounts:
          - name: device
            mountPath: /dev
          - name: sys
            mountPath: /sys
          - name: run-udev
            mountPath: /run/udev
          - name: host-root
            mountPath: /host
          - name: plugin-dir
            mountPath: /csi
          - name: kubelet-dir
            mountPath: /var/lib/kubelet
            mountPropagation: "Bidirectional"
      - name: csi-driver-registrar
        image: {{ include "mayastor.csiNode.driverRegistrar.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        args:
          - "--csi-address=$(CSI_SOCKET_ADDRESS)"
          - "--kubelet-registration-path=/var/lib/kubelet/plugins/mayastor.openebs.io/csi.sock"
          - "--v=5"
        env:
          - name: CSI_SOCKET_ADDRESS
            value: {{ .Values.csi.socketAddress | quote }}
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/sh
                - -c
                - >-
                  echo "Deleting stale file";
                  rm -rf /registration/mayastor.openebs.io /registration/mayastor.openebs.io-reg.sock;
        # Mayastor node plugin gRPC server
        ports:
          - containerPort: 10199
            name: mayastor-node
            protocol: TCP
        resources:
          limits:
            cpu: "100m"
            memory: "50Mi"
          requests:
            cpu: "100m"
            memory: "50Mi"
        volumeMounts:
          - name: plugin-dir
            mountPath: /csi
          - name: registration-dir
            mountPath: /registration
      volumes:
        - name: device
          hostPath:
            path: /dev
            type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory
        - name: run-udev
          hostPath:
            path: /run/udev
            type: Directory
        - name: host-root
          hostPath:
            path: /
            type: Directory
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/mayastor.openebs.io/
            type: DirectoryOrCreate
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory