annotations:
  category: NetworkManagement
apiVersion: v2
appVersion: v6.5.55
dependencies:
  - name: mongodb
    condition: mongodb.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 10.x.x
description: UniFi Network Application to manager UniFi devices 
home: https://github.com/startechnica/apps/tree/main/charts/unifi
icon: https://prd-www-cdn.ubnt.com/static/favicon-152.png
keywords:
  - ubiquiti
  - unifi
maintainers:
  - name: Firmansyah Nainggolan
    email: firmansyah@nainggolan.id
    url: https://firmansyah.nainggolan.id
name: unifi
sources:
  - https://www.ui.com
  - https://help.ui.com/hc/en-us/categories/200320654-UniFi-Network
version: 0.1.3
