annotations:
  category: NetworkManagement
apiVersion: v2
appVersion: v7.0.23
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - name: influxdb
    condition: influxdb.enabled
    repository: https://helm.influxdata.com
    version: 4.x.x
  - name: mongodb
    condition: mongodb.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 10.x.x
description: UniFi Network Application to manager UniFi devices 
home: https://github.com/startechnica/apps/tree/main/charts/unifi
icon: https://prd-www-cdn.ubnt.com/static/favicon-152.png
keywords:
  - ubiquiti
  - unifi
  - unifi-poller
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: Firmansyah Nainggolan
    email: firmansyah@nainggolan.id
    url: https://firmansyah.nainggolan.id
name: unifi
sources:
  - https://www.ui.com
  - https://help.ui.com/hc/en-us/categories/200320654-UniFi-Network
  - https://unpoller.com/
  - https://github.com/unifi-poller/unifi-poller
version: 0.1.1
