annotations:
  category: Storage
apiVersion: v2
appVersion: 1.0.2
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - name: etcd
    condition: etcd.enabled
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-etcd
    version: 6.x.x
  - name: nats
    condition: nats.enabled
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-nats
    version: 7.x.x
description: Mayastor is a cloud-native declarative data plane written in Rust.
  Our goal is to abstract storage resources and their differences through the data
  plane such that users only need to supply the what and do not have to worry about
  the how so that individual teams stay in control.
home: https://github.com/startechnica/apps/tree/main/charts/mayastor
icon: https://openebs.io/images/seo/openebs.png
keywords:
  - mayastor
  - openebs
maintainers:
  - name: firmansyahn
    email: firmansyah@nainggolan.id
    url: https://firmansyah.nainggolan.id
name: mayastor
sources:
  - https://github.com/openebs/mayastor
  - https://github.com/openebs/mayastor-control-plane
  - https://github.com/openebs/mayastor-api
  - https://openebs.io/docs/concepts/mayastor
  - https://mayastor.gitbook.io
type: application
version: 0.1.0
