
clusterDomain: nebula.mci.net.id
diagnosticMode:
  enabled: false

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

csiNode:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists

etcd:
  clusterDomain: nebula.mci.net.id
  persistence:
    enabled: true
    storageClass: openebs-hostpath

diskPools:
  create: true
  pools:
    - node: alberta-lin-k8m.jkt2.mci.net.id
      device: /dev/sdb
    # - node: einbech-lin-k8m.jkt2.mci.net.id
    #   device: /dev/sdb
    - node: lutie-lin-k8m.jkt2.mci.net.id
      device: /dev/sdb
    - node: rachel-lin-k8w.jkt2.mci.net.id
      device: /dev/sda
    # - node: verus-lin-k8w.jkt2.mci.net.id
    #   device: /dev/sdb

ioEngine:
  logLevel: debug
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
  extraVolumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "hugepages_2Mi_request" 
            resourceFieldRef:
              containerName: io-engine
              resource: requests.hugepages-2Mi
              divisor: 1Mi
  sidecars:
    - name: debug-probe
      image: busybox:latest
      command:
        - sh
        - -c
        - |
          echo "$(REQUESTS_HUGEPAGES_2MI)"
          ls -liah /etc/podinfo
          cat /etc/podinfo/hugepages_2Mi_request
          sleep inf
      env:
        - name: REQUESTS_HUGEPAGES_2MI
          valueFrom:
            resourceFieldRef:
              containerName: io-engine
              resource: requests.hugepages-2Mi
      volumeMounts:
        - mountPath: /etc/podinfo
          name: podinfo