
clusterDomain: nebula.mci.net.id
diagnosticMode:
  enabled: false

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

etcd:
  clusterDomain: nebula.mci.net.id
  replicaCount: 1
  revisionHistoryLimit: 2
  auth:
    rbac:
      create: true
      allowNoneAuthentication: true
      rootPassword: password
  persistence:
    enabled: true
    storageClass: openebs-hostpath

nats:
  clusterDomain: nebula.mci.net.id
  replicaCount: 1
  revisionHistoryLimit: 2
  auth:
    enabled: false
  persistence:
    enabled: false
    storageClass: openebs-hostpath

mayastorPools:
  - node: alberta-lin-k8m.jkt2.mci.net.id
    device: /dev/sdb
  - node: einbech-lin-k8m.jkt2.mci.net.id
    device: /dev/sdb
  - node: rachel-lin-k8w.jkt2.mci.net.id
    device: /dev/sdb
  - node: verus-lin-k8w.jkt2.mci.net.id
    device: /dev/sdb