{{- if and (not .Values.redis.enabled) (not .Values.tasksRedis.existingSecretName) (not .Values.cachingRedis.existingSecretName) (not .Values.redis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-external-redis" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if or .Values.redis.annotations .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.merge" (dict "values" (list .Values.redis.annotations .Values.commonAnnotations) "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  redis-cache-password: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-external-redis" .Release.Name) "key" "redis-cache-password" "length" 12 "providedValues" (list "cachingRedis.password") "context" $) }}
  redis-tasks-password: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-external-redis" .Release.Name) "key" "redis-tasks-password" "length" 12 "providedValues" (list "tasksRedis.password") "context" $) }}
{{- end }}