{{- if not (include "common.capabilities.networkingGateway.apiVersion" .) }}
{{- range $gateway := .Values.gateways }}
{{- if .enabled -}}
apiVersion: {{ include "common.capabilities.networkingGateway.apiVersion" $ }}
kind: Gateway
metadata:
  name: {{ .name }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: 
    istio.io/gateway-name: {{ .name }}
  {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" $.Values.commonLabels "context" $) | nindent 4 }}
  {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $.Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: istio
  addresses:
    - value: {{ printf "%s.%s.svc.%s" .name (include "common.names.namespace" $) $.Values.clusterDomain }}
      type: Hostname
  listeners:
    {{- if .service }}
    - name: http2
      port: {{ default 80 .service.ports.http2 | int }}
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    {{- if .service.extraPorts }}
      {{- include "common.tplvalues.render" (dict "value" .service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
    {{- else }}
    - name: http2
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}