annotations:
  category: DeveloperTools
apiVersion: v2
appVersion: 3.0.25
description: FreeRADIUS is a modular, high performance free RADIUS suite developed and 
  distributed under the GNU General Public License, version 2, and is free for download and use.
home: https://github.com/startechnica/apps/tree/main/charts/freeradius
icon: https://freeradius.org/img/wordmark.svg
keywords:
  - freeradius
  - radius
  - mysql
  - sql
maintainers:
  - name: Firmansyah Nainggolan
    email: firmansyah@nainggolan.id
    url: https://firmansyah.nainggolan.id
name: freeradius
sources:
  - https://freeradius.org/
version: 0.1.0
